// <auto-generated />
namespace WebApplication_brr_bmi1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class assalom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(assalom));
        
        string IMigrationMetadata.Id
        {
            get { return "201904050930108_assalom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
